model_path: "outputs/pretrain/Qwen2.5-1.5B-Instruct_tempowave"
dataset_path: "data/processed/pretrain/train.csv"
output_path: "outputs/continuous_pretrain/Qwen2.5-1.5B-Instruct_tempowave"
checkpoint_dir: "outputs/continuous_pretrain/Qwen2.5-1.5B-Instruct_tempowave/checkpoints"
max_seq_length: 4096
load_in_4bit: true
dataset_split: "train"
dataset_num_proc: 8
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.0
random_seed: 3407
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
save_steps: 1000
logging_steps: 20
max_steps: -1
learning_rate: 0.0001
weight_decay: 0.01
warmup_ratio: 0.05
