model_path: "outputs/pretrain/Qwen2.5-1.5B-Instruct_tempowave"
dataset_path: "data/processed/sft/train.json"
val_dataset_path: "data/processed/sft/val.json"
preview_dataset_path: "data/processed/sft/inference.json"
output_path: "outputs/sft/Qwen2.5-1.5B-Instruct_tempowave"
checkpoint_dir: "outputs/sft/Qwen2.5-1.5B-Instruct_tempowave/checkpoints"
max_seq_length: 4096
load_in_4bit: true
dataset_num_proc: 8
preview_examples: 3
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.0
random_seed: 3407
num_train_epochs: 10
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
save_steps: 5
logging_steps: 2
max_steps: -1
learning_rate: 0.0001
weight_decay: 0.01
warmup_ratio: 0.05
